after_script:
  - docker images

before_script:
  - cd "$VERSION"
  - IMAGE="litecoin-core:${VERSION}"

env:
  - VERSION=0.14
  - VERSION=0.13
  - VERSION=0.10

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Litecoin Core"

services: docker
