name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '0.18'
          - '0.17'
          - '0.16'
          - '0.15'
          - '0.14'
          - '0.13'
          - '0.10'
      fail-fast: false
    steps:
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Docker build
        id: prepare
        run: |
          function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
          LITECOIN_CORE_VERSION=${{matrix.version}}
          LATEST_LITECOIN_CORE_MAJOR_VERSION=$(ls  | grep 0 | sort -n | tail -n 1)
          PUSH=false
          REPO=uphold/litecoin-core
          TAGS=()
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            PUSH=true
            if [[ ${LITECOIN_CORE_VERSION} == *"alpine"* ]]; then
              TAGS+=("$REPO:$TAG-alpine")
            else
              TAGS+=("$REPO:$TAG")
            fi
            TAG_MAJOR_MINOR=$(echo $TAG | cut -c -4)
            if [ $(version ${TAG_MAJOR_MINOR}) -ne $(version ${LITECOIN_CORE_VERSION}) ]; then
              echo "Skipping build of base image $LITECOIN_CORE_VERSION/ as ${TAG} is targeted at ${TAG_MAJOR_MINOR}/"
              exit 0
            fi
          else
            TAGS=("$REPO:${LITECOIN_CORE_VERSION/\//-}")
            if [ $(version ${LITECOIN_CORE_VERSION}) -ge $(version ${LATEST_LITECOIN_CORE_MAJOR_VERSION}) ]; then
              echo "Version $(version ${LITECOIN_CORE_VERSION}) is greater than or equal to $(version ${LATEST_LITECOIN_CORE_MAJOR_VERSION}), tagging as latest"
              if [[ ${LITECOIN_CORE_VERSION} != *"alpine"* ]]; then
                TAGS+=("$REPO:latest")
              else
                TAGS+=("$REPO:alpine")
              fi
            fi
            if [ $GITHUB_REF == "refs/heads/master" ]; then
              PUSH=true
            fi
          fi
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=push::${PUSH}
          echo ::set-output name=tags::${TAGS[@]}
          echo ::set-env name=build::true
      - if: env.build == 'true'
        name: Login into Docker Hub
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker login --username ${DOCKER_HUB_USERNAME} --password ${DOCKER_HUB_PASSWORD}
      - if: env.build == 'true'
        name: Build Docker image
        run: |
          TAGS=(${{ steps.prepare.outputs.tags }})
          echo "Build date: ${{ steps.prepare.outputs.build_date }}"
          echo "Push: ${{ steps.prepare.outputs.push }}"
          echo "Tags: ${{ steps.prepare.outputs.tags }}"
          echo docker buildx build \
            --output "type=image,push=${{steps.prepare.outputs.push}}" \
            --progress=plain \
            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) \
            ${{ matrix.version }}/
          docker buildx build \
            --output "type=image,push=${{steps.prepare.outputs.push}}" \
            --progress=plain \
            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) \
            ${{ matrix.version }}/
      - if: env.build == 'true'
        name: Clear Docker credentials
        run: |
          rm -f ${HOME}/.docker/config.json
